#!/usr/bin/env python3
"""Generate the Fluent animation journal with environment-driven parameters.

All key simulation settings are configurable via environment variables so the
same journal template can be reused for quick smoke tests, long production
runs, and parameter sweeps without hand-editing the .jou file.

Environment variables (all have defaults):
  STHIL_N_STEPS          number of time steps to run (default 500)
  STHIL_TIME_STEP        time step size in seconds (default 0.01)
  STHIL_INNER_ITERS      inner iterations per time step (default 10)
  STHIL_AIR_VELOCITY     air inlet velocity in m/s (default 0.001)
  STHIL_HE_VELOCITY      helium inlet velocity in m/s (default 50)
  STHIL_N_PROCS          Fluent parallel procs for -tN (default 4)
  STHIL_DRIVER           graphics driver: null | opengl2 (default null)
  STHIL_CASE             input case file (default elbow_hil_ready.cas.h5)
  STHIL_SAVE_FINAL       write final case/data? 1/0 (default 1)
  STHIL_X_RES            PNG width (default 1280)
  STHIL_Y_RES            PNG height (default 720)

Controller tuning (also passed through to the UDF):
  STHIL_SETPOINT, STHIL_KP, STHIL_KI, STHIL_SLEW, STHIL_MAX_DUTY,
  STHIL_FILTER, STHIL_DEADBAND, STHIL_MIN_FRAME_EVERY, STHIL_SAVE_ALL_FRAMES,
  STHIL_FORCE_SOFTWARE

Usage:
  python3 generate_animation_journal.py
  STHIL_N_STEPS=50 STHIL_HE_VELOCITY=10 python3 generate_animation_journal.py
"""

import os
import sys

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
# Resolve ROOT from the script's location so the generator works in the main
# project or any checkpoint copy.
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FLUENT_UDF = os.path.join(ROOT, "fluent_udf")

DEFAULTS = {
    "STHIL_N_STEPS": "500",
    "STHIL_TIME_STEP": "0.01",
    "STHIL_INNER_ITERS": "10",
    "STHIL_AIR_VELOCITY": "0.001",
    "STHIL_HE_VELOCITY": "50",
    "STHIL_N_PROCS": "4",
    "STHIL_DRIVER": "null",
    "STHIL_CASE": os.path.join(FLUENT_UDF, "elbow_hil_ready.cas.h5"),
    "STHIL_SAVE_FINAL": "1",
    "STHIL_X_RES": "1280",
    "STHIL_Y_RES": "720",
}

# Pull values from environment, falling back to defaults.
env = {}
for key, default in DEFAULTS.items():
    env[key] = os.environ.get(key, default)

# Controller env vars are simply forwarded by the shell; the UDF reads them.
# We list them here so the journal header can document them.
CONTROLLER_ENVS = [
    "STHIL_SETPOINT",
    "STHIL_KP",
    "STHIL_KI",
    "STHIL_SLEW",
    "STHIL_MAX_DUTY",
    "STHIL_FILTER",
    "STHIL_DEADBAND",
    "STHIL_MIN_FRAME_EVERY",
    "STHIL_SAVE_ALL_FRAMES",
    "STHIL_FORCE_SOFTWARE",
]

n_steps = int(env["STHIL_N_STEPS"])
time_step = float(env["STHIL_TIME_STEP"])
inner_iters = int(env["STHIL_INNER_ITERS"])
air_v = float(env["STHIL_AIR_VELOCITY"])
he_v = float(env["STHIL_HE_VELOCITY"])
x_res = int(env["STHIL_X_RES"])
y_res = int(env["STHIL_Y_RES"])

frame_dir = os.path.join(FLUENT_UDF, "frames")
auto_frame = os.path.join(FLUENT_UDF, "auto_frame.jou")
out_path = os.path.join(FLUENT_UDF, "animate_hil.jou")

# ---------------------------------------------------------------------------
# Build journal
# ---------------------------------------------------------------------------
header_lines = [
    "; Fluent 2D journal: HIL animation",
    "; Auto-generated by generate_animation_journal.py",
    ";",
    "; Active parameters:",
    f";   STHIL_N_STEPS={n_steps}  STHIL_TIME_STEP={time_step}  STHIL_INNER_ITERS={inner_iters}",
    f";   STHIL_AIR_VELOCITY={air_v} m/s  STHIL_HE_VELOCITY={he_v} m/s",
    f";   STHIL_X_RES={x_res}  STHIL_Y_RES={y_res}",
    ";",
    "; Controller env vars forwarded to the UDF:",
]
for name in CONTROLLER_ENVS:
    val = os.environ.get(name, "<default>")
    header_lines.append(f";   {name}={val}")

header = "\n".join(header_lines)

body = f"""{header}
/file/set-tui-version "26.1"
chdir {FLUENT_UDF}

; Allow frame files to be overwritten without blocking the journal.
/file/confirm-overwrite? no

; Load pre-configured and UDF-hooked case
file/read-case {env['STHIL_CASE']}

; Ensure freshly compiled UDF is loaded
/define/user-defined/compiled-functions/load {FLUENT_UDF}/libudf

; Hook the FPGA feedback loop (DEFINE_ADJUST)
/define/user-defined/function-hooks/adjust
fpga_feedback_loop::libudf
""

; Hook end-of-iteration frame writer
/define/user-defined/function-hooks/execute-at-end
write_adaptive_frame::libudf
""

; Transient setup
define/models/unsteady-1st-order? yes
solve/set/transient-controls/time-step-size {time_step}
solve/set/transient-controls/number-of-time-steps 1

; Inlet velocities (can be overridden by env vars above, but the case already
; contains BCs; these journal lines are commented out to avoid prompting issues.
; Use 0_set-bc.sh to change velocities before running if needed.)
; /define/boundary-conditions/velocity-inlet velocity-inlet-5 yes yes no {air_v} no 0 no 1 no 0 no 300 no no yes 5 10 no no 0
; /define/boundary-conditions/velocity-inlet velocity-inlet-6 yes yes no {he_v} no 0 no 0 no 1 no 300 no no yes 5 10 no yes yes udf species_mass_fraction::libudf

; Initialize
solve/initialize/hyb-initialization

; Graphics setup for PNG frame export
; Working recipe in Fluent 2026 R1 null-driver mode:
;  - enable non-object-based workflow
;  - use space-separated "driver png" (slash form errors in 2026 R1)
;  - do NOT use use-window-resolution? (invalid command)
/preferences/graphics/enable-non-object-based-workflow yes
/display/set/contours/filled-contours? yes
/display/set/contours/n-contour 50
/display/set/contours/auto-range? no
/display/set/picture/driver png
/display/set/picture/x-resolution {x_res}
/display/set/picture/y-resolution {y_res}

; Create the contour object after driver/options are configured.
/display/contour he 0 1

; Initial frame
/display/save-picture {frame_dir}/helium_adaptive_0000.png
"""

footer = f"""
; Save final case/data (overwrite without interactive prompt)
/file/confirm-overwrite? no
file/write-case-data {FLUENT_UDF}/elbow_hil_final.cas.h5

exit yes
"""

with open(out_path, "w") as f:
    f.write(body)
    for i in range(1, n_steps + 1):
        f.write(f"; --- step {i} ---\n")
        f.write(f"solve/dual-time-iterate 1 {inner_iters}\n")
        f.write(f"/file/read-journal {auto_frame} ()\n")
    if env["STHIL_SAVE_FINAL"] == "1":
        f.write(footer)
    else:
        f.write("exit yes\n")

print(f"Generated {out_path} with {n_steps} steps.")
